name: Build Flutter App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          cache: true

      - name: Create Clean Flutter Project and Copy Files
        run: |
          # 1. إنشاء مشروع مؤقت بنفس اسم الحزمة
          flutter create temp_app --org com.dody --project-name dudylive --platforms android
          
          # 2. نسخ مجلد lib وملف pubspec.yaml الخاص بك إلى المشروع الجديد
          rm -rf temp_app/lib
          cp -r lib temp_app/lib
          cp pubspec.yaml temp_app/pubspec.yaml
          
          # 3. الانتقال للمشروع الجديد لبدء البناء
          cd temp_app
          flutter pub get
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: temp_app/build/app/outputs/flutter-apk/app-release.apk
